# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectperson',
            name='verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
