// Generated by CoffeeScript 1.10.0
(function() {
  var _this, applyFieldText, getWindowDimensions, handleClickOutside, positionDropdown;

  _this = this;

  getWindowDimensions = function() {
    var d, e, g, w, x, y;
    w = window;
    d = document;
    e = d.documentElement;
    g = d.getElementsByTagName('body')[0];
    x = w.innerWidth || e.clientWidth || g.clientWidth;
    y = w.innerHeight || e.clientHeight || g.clientHeight;
    return {
      width: x,
      height: y
    };
  };

  if (!opts.tags) {
    opts.tags = {
      options: [],
      tags: []
    };
  }

  if (!opts.tags.options) {
    opts.tags.options = [];
  }

  if (!opts.tags.tags) {
    opts.tags.tags = [];
  }

  handleClickOutside = function(e) {
    if (!_this.root.contains(e.target)) {
      _this.close();
    }
    _this.update();
  };

  applyFieldText = function() {
    var i, item;
    _this.selectfield.value = '';
    i = 0;
    while (i < opts.tags.options.length) {
      item = opts.tags.options[i];
      item.selected = false;
      i++;
    }
  };

  this.filterOptions = function() {
    _this.options = opts.tags.options;
    if (opts.tags.filter) {
      _this.options = _this.options.filter(function(option) {
        var attr;
        console.log(_this.options);
        attr = option[opts.tags.filter];
        return attr && attr.toLowerCase().indexOf(_this.selectfield.value.toLowerCase()) > -1;
      });
    }
    _this.trigger('filter', _this.selectfield.value);
  };

  this.ajaxFilterOptions = function(e) {
    var lookup, xhr;
    lookup = _this.selectfield.value.toLowerCase();
    if (lookup.length > opts.minlength) {
      xhr = $.get(opts.url + "?" + opts.filterfield + "=" + lookup);
      xhr.done(function() {
        _this.options = xhr.responseJSON.results;
        console.log(_this.options);
        _this.update();
        return _this.trigger('filter', _this.selectfield.value);
      });
    }
    return console.log('lookup');
  };

  positionDropdown = function() {
    var m, pos, w;
    w = getWindowDimensions();
    m = _this.root.querySelector('.menu');
    if (!m) {
      return;
    }
    if (!opts.tags.isvisible) {
      m.style.marginTop = '';
      m.style.marginLeft = '';
      return;
    }
    pos = m.getBoundingClientRect();
    if (w.width < pos.left + pos.width) {
      m.style.marginLeft = w.width - (pos.left + pos.width) - 20 + 'px';
    }
    if (pos.left < 0) {
      m.style.marginLeft = '20px';
    }
    if (w.height < pos.top + pos.height) {
      m.style.marginTop = w.height - (pos.top + pos.height) - 20 + 'px';
    }
  };

  this.navigate = function(e) {
    var activeIndex, i, item, length;
    if ([13, 38, 40].indexOf(e.keyCode) > -1 && !opts.tags.isvisible) {
      e.preventDefault();
      _this.open();
      return true;
    }
    length = _this.options.length;
    if (length > 0 && [13, 38, 40].indexOf(e.keyCode) > -1) {
      e.preventDefault();
      activeIndex = null;
      i = 0;
      while (i < length) {
        item = _this.options[i];
        if (item.active) {
          activeIndex = i;
          break;
        }
        i++;
      }
      if (activeIndex !== null) {
        _this.options[activeIndex].active = false;
      }
      if (e.keyCode === 38) {
        if (activeIndex === null || activeIndex === 0) {
          _this.options[length - 1].active = true;
        } else {
          _this.options[activeIndex - 1].active = true;
        }
      } else if (e.keyCode === 40) {
        if (activeIndex === null || activeIndex === length - 1) {
          _this.options[0].active = true;
        } else {
          _this.options[activeIndex + 1].active = true;
        }
      } else if (e.keyCode === 13 && activeIndex !== null) {
        _this.select({
          item: _this.options[activeIndex]
        });
      }
    }
    return true;
  };

  this.open = function() {
    opts.tags.isvisible = true;
    _this.trigger('open');
  };

  this.close = function() {
    if (opts.tags.isvisible) {
      opts.tags.isvisible = false;
      _this.trigger('close');
    }
  };

  this.select = function(e) {
    opts.tags.options.forEach(function(i) {
      return i.selected = false;
    });
    e.item.selected = true;
    _this.addTag(e.item);
    applyFieldText();
    _this.filterOptions();
    _this.trigger('select', e.item);
  };

  this.addTag = function(item) {
    if (opts.tags.tags.indexOf(item) === -1) {
      opts.tags.tags.push(item);
    }
  };

  this.removeTag = function(e) {
    opts.tags.tags = opts.tags.tags.filter(function(tag) {
      if (tag._id !== e.item._id) {
        return tag;
      }
    });
  };

  this.on('mount', function() {
    applyFieldText();
    _this.filterOptions();
    document.addEventListener('click', handleClickOutside);
    _this.update();
  });

  this.on('update', function() {
    opts.tags.options.forEach(function(item) {
      item._id = item._id || (Math.floor(Math.random() * 60466175) + 1679615).toString(36);
    });
    opts.tags.tags.forEach(function(tag) {
      tag._id = tag._id || (Math.floor(Math.random() * 60466175) + 1679615).toString(36);
    });
    if (!opts.tags.filter) {
      applyFieldText();
    }
    positionDropdown();
  });

  this.on('unmount', function() {
    document.removeEventListener('click', handleClickOutside);
  });

}).call(this);
