// Generated by CoffeeScript 1.10.0
(function() {
  var self;

  self = this;

  self.options = [];

  self.results = [];

  self.on('mount', function() {});

  this.loadoptions = function(e) {
    var lookup, xhr;
    lookup = $(e.target).val();
    if (lookup.length > opts.minlength) {
      xhr = $.get(opts.url + "?" + opts.filter + "=" + lookup);
      xhr.done(function() {
        self.results = xhr.responseJSON;
        return self.update();
      });
    }
    return console.log('lookup');
  };

  this.tag_selected = function(e) {
    console.log(e.item.name);
    console.log(e.item.id);
    console.log('Item selected');
    RiotControl.trigger('tag_selected', e);
    console.log('triggered RC');
    return false;
  };

}).call(this);
