// Generated by CoffeeScript 1.10.0
(function() {
  var ping, self;

  self = this;

  self.message = "Projects";

  self.projects = [];

  self.edit_project = function(e) {
    riot.route("project/" + this.id + "/detail");
    return RiotControl.trigger('load_project_detail', this);
  };

  self.on('mount', function() {});

  RiotControl.on('projects_changed', function(projects, page, count, page_size) {
    self.projects = projects;
    self.page = page;
    self.page_size = page_size;
    self.count = count;
    self.pages = Math.ceil(self.count / self.page_size);
    console.log(self);
    console.log('update');
    return self.update();
  });

  self.set_page = function(e) {
    var opts, page;
    page = $(e.target).attr('data-set-page');
    opts = {
      page: page || 1,
      per_page: 50,
      filters: $('form#project-filter').serialize()
    };
    return RiotControl.trigger('projects_reload', opts);
  };

  self.ping = function() {
    return alert('ping');
  };

  ping = function() {
    return alert('ping');
  };

}).call(this);
