// Generated by CoffeeScript 1.10.0
(function() {
  var self;

  self = this;

  self.message = "Projects";

  self.project = void 0;

  self.on('mount', function() {});

  this.load_project = function(project) {
    $('project-detail').show();
    $('project-list').hide();
    self.project = project;
    return self.update();
  };

  self.project_list = function() {
    riot.route('project/list');
    return RiotControl.trigger('load_project_list');
  };

  RiotControl.on('load_project_detail', function(project) {
    console.log(project);
    return self.load_project(project);
  });

  RiotControl.on('load_project_list', function() {
    $('project-list').show();
    return $('project-detail').hide();
  });

}).call(this);

//# sourceMappingURL=project_detail.tag.js.map
