// Generated by CoffeeScript 1.10.0
(function() {
  riot.route(function(collection, id, action) {
    if (collection === 'project' && id === 'list') {
      return RiotControl.trigger('load_project_list');
    }
  });

  riot.route.start();

}).call(this);
