# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 13:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('post', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
                ('state', models.CharField(choices=[('A', 'Accepted'), ('X', 'Rejected'), ('W', 'Waiting')], max_length=2)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_audited', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_created', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
