# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsontag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objecttag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
